export const getColor = (mimeType: string) => {
    switch (mimeType) {
        case "text/plain":
            return "bg-gray-700";
        case "text/csv":
            return "bg-green-400";
        case "text/html":
            return "bg-yellow-100";
        case "application/javascript":
            return "bg-teal-400";
        case "application/xml":
        case "text/xml":
            return "bg-purple-500";
        case "text/css":
            return "bg-blue-300";
        case "application/json":
            return "bg-blue-200";
        case "application/pdf":
            return "bg-red-600";
        case "application/msword":
        case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
            return "bg-blue-500";
        case "application/vnd.ms-powerpoint":
        case "application/vnd.openxmlformats-officedocument.presentationml.presentation":
            return "bg-orange-400";
        case "application/vnd.ms-excel":
        case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
            return "bg-green-600";
        case "application/vnd.rar":
            return "bg-purple-700";
        case "application/zip":
            return "bg-indigo-700";
        case "application/x-sh":
            return "bg-green-800";
        case "audio/mpeg":
        case "audio/wav":
            return "bg-pink-400";
        case "video/mp4":
        case "video/mpeg":
            return "bg-blue-800";
        case "audio/ogg":
            return "bg-yellow-500";
        case "audio/flac":
            return "bg-purple-600";
        case "image/jpeg":
        case "image/png":
        case "image/gif":
        case "image/webp":
        case "image/svg+xml":
            return "bg-teal-400";
        case "image/tiff":
            return "bg-orange-300";
        case "font/woff":
        case "font/woff2":
        case "application/x-font-woff":
            return "bg-teal-300";
        case "application/octet-stream":
            return "bg-gray-600";
        case "application/x-bzip2":
            return "bg-red-500";
        case "application/x-gzip":
            return "bg-green-500";
        case "application/x-7z-compressed":
            return "bg-indigo-500";
        default:
            return "bg-gray-300";
    }
};
